export = {
    token: process.env.token,
    mongodb: process.env.db,
    prefix: "!",
    devs: ["2"],
    emojis: {
        check: "✅",
        error: "❌",
        one: "1️⃣",
        two: "2️⃣",
        three: "3️⃣",
        four: "4️⃣",
        five: "5️⃣",
        six: "6️⃣",
        seven: "7️⃣",
        eight: "8️⃣",
        nine: "9️⃣",
        ten: "🔟",
        zero: "0️⃣",
        leftArrow: "▶",
        rightArrow: "◀",
        upArrow: "🔼",
        downArrow: "🔽",
    },
    botname: "Plex",
    status: [
        {
            name: "{serversCount} servers",
            type: "WATCHING",
        },
    ],
    colors: {
        darkRed: "#922B21",
        red: "#C0392B  ",
        lightRed: "#FF2D00",
        brown: "##6E2C00",
        orange: "#FF6800",
        yellow: "#F4D03F",
        green: "#27AE60 ",
        lightBlue: "#00FFDC",
        blue: "#1327D6",
        purple: "#9E13D6",
    },
};
